Google login
hieuneko/BookStoreApi pull request #12
Opened 2023-03-30 09:02 UTC by hieuneko

- Add firebase account json file and library
- Add google login endpoint
- Google login page
- Add supply error for google login service

2023-03-30 09:22 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/FirebaseInitializer.java
> +            InputStream serviceAccount = FirebaseInitializer.class.getResourceAsStream("/BookApiAccountKey.json");
```suggestion
            final InputStream serviceAccount = FirebaseInitializer.class.getResourceAsStream("/BookApiAccountKey.json");
```

2023-03-30 09:22 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/FirebaseInitializer.java
> +            GoogleCredentials credentials = GoogleCredentials.fromStream(serviceAccount);
```suggestion
            final GoogleCredentials credentials = GoogleCredentials.fromStream(serviceAccount);
```

2023-03-30 09:22 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/FirebaseInitializer.java
> +            FirebaseOptions options = new FirebaseOptions.Builder()
```suggestion
            final FirebaseOptions options = new FirebaseOptions.Builder()
```

2023-03-30 09:22 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/api/auth/AuthController.java
> +        return JwtTokenResponseDTO.builder()
Hơi giống code bên login username/password --> refactor

2023-03-30 09:22 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/JWTWebSecurityConfig.java
> +                .antMatchers("/**").permitAll()
Sao chơi thế này được

2023-03-30 09:22 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/AuthError.java
> +    public static Supplier<BadRequestException> supplyProjectIdIncorrect() {
Bên facebook có đổi lại: nếu chưa có thì tạo mới nên bên này cũng đổi lại vậy luôn nha

2023-03-30 09:22 UTC, voquanghoa commented on src/main/resources/application.properties
> +spring.security.oauth2.client.registration.google.client-secret=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
Đưa sang file application-DEV.properties

2023-03-30 09:22 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/MyFirebaseToken.java
> +public class MyFirebaseToken {
Tên class này không tốt. Có thể là `FirebaseTokenPayload`

2023-03-31 09:01 UTC, hieuneko commented on src/main/java/com/phamhieu/bookapi/domain/auth/AuthError.java
> +    public static Supplier<BadRequestException> supplyProjectIdIncorrect() {
này e check project id thôi a, cái supply not found khi tìm ko thấy trong hệ thống thì e xóa sau khi thêm phần tạo mới use nếu ko có rồi ạ

2023-03-31 10:55 UTC, voquanghoa commented
Không chạy được 
![image](https://user-images.githubusercontent.com/10450325/229101990-5199773b-cc72-494d-8abe-249b2f860a10.png)

2023-04-07 03:06 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleLoginService.java
> +                    return new JwtUserDetails(newUser, authorities);
Extract làm hàm riêng

2023-04-07 03:06 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleTokenVerifierService.java
> +    private static final String CLIENT_ID="117223285300-7v6i7cfgmlgalskig5s1ukinggd1cnn1.apps.googleusercontent.com";
Đưa vào properties file

2023-04-07 03:06 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleTokenVerifierService.java
> +                .build();
Đưa vào bean hoặc khởi tạo trong constructor

2023-04-07 03:06 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/api/auth/AuthControllerTest.java
> +        when(jwtTokenService.generateToken(userDetails)).thenReturn(token);
phải có verify cái đã mock

2023-04-07 04:56 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/JWTWebSecurityConfig.java
> +    public CorsFilter corsFilter() {
không hiểu lắm, frontend cùng port mà sao phải thêm cái này

2023-04-07 05:07 UTC, hieuneko commented on src/main/java/com/phamhieu/bookapi/configuration/JWTWebSecurityConfig.java
> +    public CorsFilter corsFilter() {
Dạ em chạy bằng node js nên index trên port khác a, để chung nó sẽ bắt mình login google 2 lần nếu vào web lần đầu

2023-04-07 05:08 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/JWTWebSecurityConfig.java
> +    public CorsFilter corsFilter() {
Có thể làm đơn giản đừng dùng nodejs được ko. Tham khảo của Tuấn xem, hoặc tạo 1 endpoint home trả về html thôi

2023-04-07 06:37 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleTokenVerifierService.java
> +                .build();
đưa vào bean, singletonList static import

2023-04-07 06:45 UTC, hieuneko commented on src/main/java/com/phamhieu/bookapi/configuration/JWTWebSecurityConfig.java
> +    public CorsFilter corsFilter() {
em thử đưa vào 1 endpoint rồi mà  vừa vào 8080 thì nó vẫn redirect đến trang login/oauth2/code/google của google trước rồi mới sang index a, sau đó nó lấy cái giá trị mình login vào để chạy khi bấm nút login ở index, thành ra mình login 2 lần. Bữa trước tuấn cũng nói e là hắn cũng bị 2 lần login vầy đó a

2023-04-07 07:02 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/JWTWebSecurityConfig.java
> +    public CorsFilter corsFilter() {
Vấn đề không phải là bao nhiêu lần. Vấn đề là đừng dùng NodeJS nữa, phần frontend này sẽ thuộc về Spring Bot, chung domain và không có vụ cors này

2023-04-07 08:00 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleLoginService.java
> +        final Collection<? extends GrantedAuthority> authorities =
Tại sao ở đây chắc chắn là CONTRIBUTOR

2023-04-07 08:00 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/persistence/role/RoleRepository.java
> +    @Query("SELECT c from RoleEntity c WHERE c.name = :roleName")
Query không cần.

2023-04-07 08:00 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/persistence/role/RoleStore.java
> +        return roleRepository.findByName(roleName).get().getId();
chắc có warning ở đây

2023-04-07 09:05 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleLoginService.java
> +    private Collection<? extends GrantedAuthority> createGoogleUserAuthorities(final String role) {
Cái này thật ra không liên quan gì đến logic của google

```suggestion
    private Collection<? extends GrantedAuthority> createAuthorities(final String role) {
```

2023-04-07 09:05 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleLoginService.java
> +        final String newGoogleUserRole = "CONTRIBUTOR";
Hoặc là truyền trực tiếp hoặc là khai báo cái này thành private static final String ....

2023-04-07 09:05 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleLoginService.java
> +        userStore.create(newUser);
extract thành 1 hàm và trả về user

2023-04-07 09:05 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleLoginService.java
> +                })
extract thành hàm

2023-04-07 09:05 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleTokenVerifierService.java
> +                    .build();
Tách thành mapper

```suggestion
            return toGoogleTokenPayload(payload);
```

2023-04-07 09:06 UTC, hieuneko commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleLoginService.java
> +    private Collection<? extends GrantedAuthority> createGoogleUserAuthorities(final String role) {
e tạo để nó đỡ trùng khi gọi nhiều lần a

2023-04-07 10:39 UTC, voquanghoa approved these changes

2023-04-07 10:41 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/GoogleTokenVerifierConfig.java
> +    private String CLIENT_ID;
sai convention tên biến

2023-04-07 10:42 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/GoogleTokenVerifierConfig.java
> +    public GoogleIdTokenVerifier tokenVerify() {
```suggestion
    public GoogleIdTokenVerifier tokenVerify(@Value("spring.security.oauth2.client.registration.google.client-id") final String clientId) {
```

2023-04-07 10:43 UTC, voquanghoa commented on src/main/resources/application-dev.properties
> +spring.security.oauth2.client.registration.google.client-secret=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
Check nếu 2 config này chỉ dùng để lấy ra từ code java của mình thì để cái key ngắn lại

2023-04-07 10:43 UTC, voquanghoa commented on src/main/resources/application-dev.properties
> +# OAuth
Đổi tên `dev` --> `DEV` viết hoa

2023-04-07 10:44 UTC, voquanghoa commented on src/main/resources/application.properties
> +spring.flyway.locations=classpath:db/migration/COMMON,classpath:db/migration/DEV
Nhân tiện

Ở file `application.properties`

```suggestion
spring.flyway.locations=classpath:db/migration/COMMON
```

Ở file

application-DEV.properties

```
spring.flyway.locations=classpath:db/migration/COMMON,classpath:db/migration/DEV
```

2023-04-07 11:16 UTC, hieuneko commented on src/main/java/com/phamhieu/bookapi/configuration/GoogleTokenVerifierConfig.java
> +    public GoogleIdTokenVerifier tokenVerify() {
bỏ trực tiếp vào param thì nó ko nhận được cái giá trị value dù truyền qua a, nên e vẫn để ở lớp config

2023-04-07 11:17 UTC, hieuneko commented on src/main/resources/application-dev.properties
> +spring.security.oauth2.client.registration.google.client-secret=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
2 config này nếu ko ghi đủ theo key thì nó ko nhận được để tạo ra bean được a

2023-04-07 11:52 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/GoogleTokenVerifierConfig.java
> +    public GoogleIdTokenVerifier tokenVerify() {
Em có hiểu @Bean là gì không vậy???

2023-04-07 11:53 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/GoogleTokenVerifierConfig.java
> +    public GoogleIdTokenVerifier tokenVerify() {
Anh comment dùng Bean thế là cứ dùng và không quan tâm nó là cái gì và cách dùng của nó???

2023-04-07 11:54 UTC, voquanghoa requested changes
Rework!!!

2023-04-09 08:17 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleTokenVerifierService.java
> +public class GoogleTokenVerifierService {
@AllRequireArgs

2023-04-09 08:17 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/auth/GoogleTokenVerifierService.java
> +    public GoogleTokenVerifierService(GoogleIdTokenVerifier tokenVerifier) {
Remove

2023-04-09 16:44 UTC, voquanghoa commented on build.gradle
> +    implementation group: 'org.springframework.social', name: 'spring-social-google', version: '1.0.0.RELEASE'
Cái này có vẻ không cần

2023-04-09 16:44 UTC, voquanghoa commented on src/main/resources/templates/index.html
> +        gapi.load('auth2', function() {
Thử dùng code hôm trước gửi xem

2023-04-10 02:42 UTC, hieuneko commented on src/main/resources/templates/index.html
> +        gapi.load('auth2', function() {
chạy code trước a gửi nó ra 1 idToken của firebase có dạng khác phải dùng thư viện của firebase mới đọc được a, bữa trước e dùng cách này mà a mẫn nói ko cần nên kêu em đổi sang dùng của google thôi

2023-04-10 02:46 UTC, voquanghoa commented on src/main/resources/templates/index.html
> +        gapi.load('auth2', function() {
Thì thử dùng đi, cái đó đơn giản hơn

2023-04-10 02:47 UTC, voquanghoa commented on src/main/resources/templates/index.html
> +        gapi.load('auth2', function() {
Lý do là cái frontend đang chạy có vấn đề. Hoặc là fix được nó hoặc dùng cách dễ hơn kia

2023-04-10 07:16 UTC, voquanghoa approved these changes

2023-04-10 07:16 UTC, merged