Crud book
hieuneko/BookStoreApi pull request #6
Opened 2023-03-14 03:36 UTC by hieuneko

create crud book with unit test

2023-03-14 10:50 UTC, voquanghoa requested changes

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/book/BookService.java
> +        Book tempBook = findById(bookId);
```suggestion
        final Book existingBook = findById(bookId);
```

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/configuration/ContactAppConfig.java
> +public class ContactAppConfig {
Cái này chắc không cần đâu

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/api/book/BookResponseDTO.java
> +    private LocalDateTime createdAt;
Dùng Instant thay vì LocalDateTime

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/api/book/BookResponseDTO.java
> +import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
Xoá import không dùng

2023-03-14 10:50 UTC, voquanghoa commented on build.gradle
> +    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.13.3'
Kiểm tra cái này có cần không, thử bỏ đi xem (sau khi chuyển về instant)

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/book/Book.java
> +    private LocalDateTime updatedAt;
Dùng Instant

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/book/Book.java
> +import java.time.LocalDateTime;
Chú ý import dư

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/book/BookService.java
> +        bookStore.delete(bookId);
Chưa check book có tồn tại

2023-03-14 10:50 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/persistence/book/BookRepository.java
> +    List<BookEntity> findAllByTitleOrAuthorOrDescription(final String keyword);
Dùng @Query rồi thì tên có thể gọn lại

2023-03-14 10:50 UTC, voquanghoa commented on src/main/resources/db/migration/COMMON/V1_0_0_202303021102__create_table_book.sql
> +INSERT INTO books(title, author, description, user_id)
Dừng sửa file như thế này, tạo migration mới.

2023-03-14 10:50 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/api/book/BookControllerTest.java
> +    private static final DateTimeFormatter pattern = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSSS");
Check lại vụ format sau khi đổi kiểu về Instant

2023-03-14 10:50 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/domain/book/BookServiceTest.java
> +        assertThrows(NotFoundException.class, () -> bookService.findById(id));
????

2023-03-14 10:50 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/domain/book/BookValidationTest.java
> +        final var book = buildBook();
@With

2023-03-14 10:50 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/persistence/book/BookStoreTest.java
> +        final var book = buildBookEntity();
```suggestion
        final var bookId = randomUUI();
```

2023-03-15 04:56 UTC, hieuneko commented on src/test/java/com/phamhieu/bookapi/domain/book/BookServiceTest.java
> +        assertThrows(NotFoundException.class, () -> bookService.findById(id));
em copy test từ bài java template lúc mới học spring làm để test thử sang bài này mà quên thêm phần check id trên hàm delete khi viết lại :P

2023-03-15 04:58 UTC, hieuneko commented on src/test/java/com/phamhieu/bookapi/api/book/BookControllerTest.java
> +    private static final DateTimeFormatter pattern = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSSSSS");
em đổi sang instant thì ko cần format chạy vẫn được nhưng cái hàm update thì lại dính lỗi format khi toString nên em fix cứng trong build luôn rồi a

2023-03-16 01:58 UTC, voquanghoa approved these changes

2023-03-16 01:58 UTC, voquanghoa commented on src/main/java/com/phamhieu/bookapi/domain/book/BookValidation.java
> +    public void validateBookInformation(final Book book) {
```suggestion
    public void validateBook(final Book book) {
```

2023-03-16 01:58 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/api/book/BookControllerTest.java
> +        this.mvc.perform(MockMvcRequestBuilders.get(BASE_URL + "/search?keyword=" + anyString()))
Refactoring

2023-03-16 01:58 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/api/book/BookResponseDTOMapperTest.java
> +        assertEquals(bookDTO.getId(), book.getId());
Đưa book lên trước

2023-03-16 01:58 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/domain/book/BookServiceTest.java
> +        assertEquals(book.getId(), actual.getId());
```suggestion
        assertEquals(book, actual);
```
Là đủ

2023-03-16 01:58 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/domain/book/BookServiceTest.java
> +        assertThrows(NotFoundException.class, () -> bookService.findById(id));
Vẫn ko sửa

2023-03-16 01:58 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/domain/book/BookValidationTest.java
> +        validateBookInformation(book);
```suggestion
        assertDoesnotThrow(() -> validateBookInformation(book));
```

2023-03-16 01:58 UTC, voquanghoa commented on src/test/java/com/phamhieu/bookapi/persistence/book/BookStoreTest.java
> +        bookStore.delete(bookId);
Dùng assertDoesNotThrow

2023-03-16 01:59 UTC, voquanghoa commented
Refactor test controller

2023-03-16 04:10 UTC, merged